// Generated by CoffeeScript 1.4.0
(function() {
  var bind, emit;

  emit = function($item, item) {
    return $item.append("<p>Hello Linkmap</p>");
  };

  bind = function($item, item) {
    var progress, socket;
    socket = new WebSocket('ws://' + window.document.location.host + '/plugin/linkmap');
    progress = function(m) {
      return wiki.log('linkmap', m);
    };
    socket.onopen = function() {
      return progress("opened");
    };
    socket.onmessage = function(e) {
      progress(e.data);
      return socket.close();
    };
    return socket.onclose = function() {
      return progress("closed");
    };
  };

  window.plugins.linkmap = {
    emit: emit,
    bind: bind
  };

}).call(this);
