// Generated by CoffeeScript 1.4.0
(function() {
  var bind, emit, forceData, linkmap, progress, socket;

  linkmap = {};

  forceData = function() {
    var div, i, link, links, nodeGroup, nodeNum, nodes, slug, slugs, source, target, _i, _j, _len, _len1, _ref;
    nodes = [];
    links = [];
    nodeNum = {};
    nodeGroup = {};
    _ref = $('.page');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      div = _ref[_i];
      nodeGroup[div.id] = 1;
    }
    for (slug in linkmap) {
      nodeNum[slug] = nodes.length;
      nodes.push({
        name: slug,
        group: nodeGroup[slug] || 3
      });
    }
    for (slug in linkmap) {
      slugs = linkmap[slug];
      source = nodeNum[slug];
      for (i = _j = 0, _len1 = slugs.length; _j < _len1; i = ++_j) {
        link = slugs[i];
        if (i < 4 && ((target = nodeNum[link]) != null)) {
          links.push({
            source: source,
            target: target,
            value: 6
          });
        }
      }
    }
    return {
      nodes: nodes,
      links: links
    };
  };

  emit = function($item, item) {
    return $item.append("<p>Hello Linkmap</p>");
  };

  bind = function($item, item) {
    $item.addClass('force-source');
    return $item.get(0).forceData = forceData;
  };

  socket = new WebSocket('ws://' + window.document.location.host + '/plugin/linkmap');

  progress = function(m) {
    return wiki.log('linkmap', m);
  };

  socket.onopen = function() {
    return progress("opened");
  };

  socket.onmessage = function(e) {
    linkmap = JSON.parse(e.data);
    return socket.close();
  };

  socket.onclose = function() {
    return progress("closed");
  };

  window.plugins.linkmap = {
    emit: emit,
    bind: bind
  };

}).call(this);
