// Generated by CoffeeScript 1.4.0
(function() {
  var WebSocketServer, buildmap, startServer;

  WebSocketServer = require('ws').Server;

  buildmap = function(done) {
    return done({
      nodes: [],
      links: []
    });
  };

  startServer = function(params) {
    var k, linkmap, socket, v;
    console.log('linkmap startServer', (function() {
      var _results;
      _results = [];
      for (k in params) {
        v = params[k];
        _results.push(k);
      }
      return _results;
    })());
    linkmap = "{}";
    buildmap(function(map) {
      linkmap = JSON.stringify(map, null, 2);
      return console.log('linkmap buildmap', linkmap);
    });
    socket = new WebSocketServer({
      server: params.server,
      path: '/plugin/linkmap'
    });
    return socket.on('connection', function(ws) {
      console.log('connection established, ready to send');
      return ws.send(linkmap, function(err) {
        if (err) {
          return console.log('unable to send ws message:', err);
        }
      });
    });
  };

  module.exports = {
    startServer: startServer
  };

}).call(this);
