// Generated by CoffeeScript 1.3.3
(function() {
  var constructor, listItemHtml;

  listItemHtml = function(slug, wikiPage) {
    return "<li>\n  <a class=\"internal\" href=\"#\" title=\"origin\" data-page-name=\"" + slug + "\"> \n    " + wikiPage.title + "\n  </a> \n  <button>✕</button>\n</li>";
  };

  constructor = function($, dependencies) {
    var bind, emit, localStorage;
    if (dependencies == null) {
      dependencies = {};
    }
    localStorage = dependencies.localStorage || window.localStorage;
    emit = function($div, item) {
      var i, slug, ul, wikiPage, _i, _ref, _results;
      if (localStorage.length === 0) {
        $div.append('<p>empty</p>');
        return;
      }
      $div.append(ul = $('<ul />'));
      _results = [];
      for (i = _i = 0, _ref = localStorage.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        slug = localStorage.key(i);
        wikiPage = JSON.parse(localStorage.getItem(slug));
        _results.push(ul.prepend(listItemHtml(slug, wikiPage)));
      }
      return _results;
    };
    bind = function($div, item) {
      return $div.on('click', 'button', function() {
        var slug;
        slug = $(this).siblings('a.internal').data('pageName');
        localStorage.removeItem(slug);
        return emit($div.empty(), item);
      });
    };
    return {
      emit: emit,
      bind: bind
    };
  };

  wiki.registerPlugin('changes', constructor);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = constructor;
  }

}).call(this);
