// Generated by CoffeeScript 1.3.3
(function() {
  var constructor;

  constructor = function($, dependencies) {
    var localStorage;
    if (dependencies == null) {
      dependencies = {};
    }
    localStorage = dependencies.localStorage || window.localStorage;
    return {
      emit: function($div, item) {
        var i, slug, ul, wikiPage, _i, _ref, _results;
        $div.append(ul = $('<ul />'));
        if (localStorage.length === 0) {
          ul.append('<p>empty</p>');
        }
        _results = [];
        for (i = _i = 0, _ref = localStorage.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          slug = localStorage.key(i);
          wikiPage = JSON.parse(localStorage[slug]);
          _results.push(ul.prepend("<li>\n  <a class=\"internal\" href=\"#\" title=\"origin\" data-page-name=\"" + slug + "\"> \n    " + wikiPage.title + "\n  </a> \n  <button>X</button>\n</li>"));
        }
        return _results;
      },
      bind: function($div, item) {
        return $div.find('button').click(function() {
          var slug;
          slug = $(this).siblings('a.internal').data('pageName');
          localStorage.removeItem(slug);
          return plugin["do"]($div.empty(), item);
        });
      }
    };
  };

  wiki.registerPlugin('changes', constructor);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = constructor;
  }

}).call(this);
