// Generated by CoffeeScript 1.4.0
(function() {

  window.plugins.efficiency = {
    efficiencyDIV: null,
    emit: function(div, item) {
      wiki.log('efficiency', div, item);
      div.addClass('data');
      $('<p />').addClass('readout').appendTo(div).text("0%");
      this.efficiencyDIV = div;
      return $('<p />').html(wiki.resolveLinks(item.text || 'efficiency')).appendTo(div);
    },
    bind: function(div, item) {
      var calculate, calculatePercentage, calculateStrategy_GrayBinary, calculateStrategy_GrayIterativeClustering, getImageData, lastThumb, locate, setEfficiencyReadoutValue,
        _this = this;
      lastThumb = null;
      div.find('p:first').dblclick(function(e) {
        return wiki.dialog("JSON for " + item.text, $('<pre/>').text("something good"));
      });
      div.find('p:last').dblclick(function() {
        return wiki.textEditor(div, item);
      });
      locate = function() {
        var idx, who;
        idx = $('.item').index(div);
        who = $(".item:lt(" + idx + ")").filter('.image').toArray().reverse();
        return who.last();
      };
      calculate = function(div) {
        var data, value;
        data = getImageData(div);
        value = calculatePercentage(data);
        return setEfficiencyReadoutValue(value);
      };
      getImageData = function(div) {
        var c, d, imageData, img, src;
        src = $(div).find('img').get(0);
        c = $('<canvas id="myCanvas" width="200" height="100" style="border:1px solid #c3c3c3;">');
        d = c.get(0).getContext("2d");
        img = new Image();
        img.src = src;
        d.drawImage(src, 0, 0);
        imageData = d.getImageData(0, 0, 200, 100);
        return imageData.data;
      };
      calculatePercentage = function(data) {
        return calculateStrategy_GrayBinary(data);
      };
      setEfficiencyReadoutValue = function(value) {
        var note;
        note = '%</p><p>Pattern Efficiency from Photographic Statistics</p>';
        if (_this.efficiencyDIV) {
          return $(_this.efficiencyDIV)[0].innerHTML = '<p class="readout">' + value + note;
        }
      };
      calculateStrategy_GrayBinary = function(data) {
        var B, G, R, i, l, luma, lumaHighCount, lumaLowCount, lumaMax, lumaMid, lumaMin, lumas, numPix, percentage, _i, _j, _len;
        numPix = data.length / 4;
        lumaMin = 255;
        lumaMax = 0;
        lumas = [];
        for (i = _i = 0; 0 <= numPix ? _i <= numPix : _i >= numPix; i = 0 <= numPix ? ++_i : --_i) {
          R = data[i * 4 + 0];
          G = data[i * 4 + 1];
          B = data[i * 4 + 2];
          luma = lumas[i] = 0.299 * R + 0.587 * G + 0.114 * B;
          if (luma > lumaMax) {
            lumaMax = luma;
          }
          if (luma < lumaMin) {
            lumaMin = luma;
          }
        }
        lumaMid = (lumaMax - lumaMin) / 2;
        lumaLowCount = 0;
        lumaHighCount = 0;
        for (_j = 0, _len = lumas.length; _j < _len; _j++) {
          l = lumas[_j];
          if (l <= lumaMid) {
            lumaLowCount++;
          } else {
            lumaHighCount++;
          }
        }
        percentage = lumaHighCount / numPix * 100;
        return percentage;
      };
      calculateStrategy_GrayIterativeClustering = function(data) {
        var B, G, MAX_TRIES, R, THRESHOLD_CONVERGENCE_GOAL, high, i, l, low, luma, lumaAvgHigh, lumaAvgLow, lumaHighCount, lumaHighTotal, lumaLowCount, lumaLowTotal, lumaMax, lumaMin, lumas, lumasHigh, lumasLow, numPix, numTries, percentage, threshold, thresholdDiff, thresholdInitial, _i, _j, _k, _l, _len, _len1, _len2;
        THRESHOLD_CONVERGENCE_GOAL = 5;
        MAX_TRIES = 10;
        numPix = Math.floor(data.length / 4);
        lumaMin = 255;
        lumaMax = 0;
        lumas = [];
        for (i = _i = 0; 0 <= numPix ? _i <= numPix : _i >= numPix; i = 0 <= numPix ? ++_i : --_i) {
          R = data[i * 4 + 0];
          G = data[i * 4 + 1];
          B = data[i * 4 + 2];
          luma = lumas[i] = 0.299 * R + 0.587 * G + 0.114 * B;
          if (luma > lumaMax) {
            lumaMax = luma;
          }
          if (luma < lumaMin) {
            lumaMin = luma;
          }
        }
        thresholdInitial = (lumaMax - lumaMin) / 2;
        threshold = thresholdInitial;
        lumaHighCount = 0;
        numTries = 0;
        while (numTries < MAX_TRIES) {
          numTries++;
          lumasLow = [];
          lumasHigh = [];
          lumaLowCount = 0;
          lumaHighCount = 0;
          for (_j = 0, _len = lumas.length; _j < _len; _j++) {
            l = lumas[_j];
            if (l <= threshold) {
              lumasLow.push(l);
              lumaLowCount++;
            } else {
              if (l !== NaN) {
                lumasHigh.push(l);
                lumaHighCount++;
              }
            }
          }
          lumaLowTotal = 0;
          for (_k = 0, _len1 = lumasLow.length; _k < _len1; _k++) {
            low = lumasLow[_k];
            if (!isNaN(low)) {
              lumaLowTotal += low;
            } else {
              wiki.log('Found a NaN low ', low);
            }
          }
          lumaAvgLow = 0;
          if (lumaLowCount > 0) {
            lumaAvgLow = lumaLowTotal / lumaLowCount;
          }
          lumaHighTotal = 0;
          wiki.log('lumasHigh ', lumasHigh);
          for (_l = 0, _len2 = lumasHigh.length; _l < _len2; _l++) {
            high = lumasHigh[_l];
            if (!isNaN(high)) {
              lumaHighTotal += high;
            } else {
              wiki.log('Found a NaN high', high);
            }
          }
          lumaAvgHigh = 0;
          if (lumaHighCount > 0) {
            lumaAvgHigh = lumaHighTotal / lumaHighCount;
          }
          wiki.log('lumaLowCount ', lumaLowCount, '  lumaHighCount ', lumaHighCount);
          wiki.log('lumaLowTotal ', lumaLowTotal, '  lumaHighTotal ', lumaHighTotal);
          wiki.log('lumaAvgLow ', lumaAvgLow, '  lumaAvgHigh ', lumaAvgHigh);
          threshold = (lumaAvgHigh - lumaAvgLow) / 2;
          thresholdDiff = Math.abs(threshold - thresholdInitial);
          wiki.log('numTries ', numTries, '  thresholdDiff ', thresholdDiff, '  thresholdInitial ', thresholdInitial, '  threshold new ', threshold);
          if (thresholdDiff <= THRESHOLD_CONVERGENCE_GOAL || numTries > MAX_TRIES) {
            wiki.log("we're done");
            break;
          } else {
            thresholdInitial = threshold;
          }
        }
        percentage = lumaHighCount / numPix * 100;
        if (percentage > 100.0) {
          percentage = 100;
        }
        return percentage;
      };
      return calculate(locate());
    }
  };

}).call(this);
