// Generated by CoffeeScript 1.4.0
(function() {
  var WebSocketServer, child, fetchPage, fs, radio, startRadio, startServer, status;

  WebSocketServer = require('ws').Server;

  fs = require('fs');

  child = require('child_process');

  fetchPage = function(path, done) {
    var text;
    return text = fs.readFile(path, 'utf8', function(err, text) {
      if (err) {
        return console.log(['twadio fetchPage error', path, err]);
      }
      return done(JSON.parse(text));
    });
  };

  status = {
    pid: null,
    freq: 14.042,
    mode: null
  };

  radio = null;

  startRadio = function(message) {
    radio = child.spawn('/usr/bin/ruby', [__dirname + '/twadio.rb', status.mode, status.freq, '0', '1', '.5', message]);
    status.pid = radio.pid;
    console.log("twadio start", radio.pid);
    return radio.on('exit', function(code, signal) {
      console.log('twadio exit', code, signal);
      status.mode = null;
      status.pid = null;
      return radio.emit('update');
    });
  };

  startServer = function(params) {
    var k, server, v;
    console.log('twadio startServer', (function() {
      var _results;
      _results = [];
      for (k in params) {
        v = params[k];
        _results.push(k);
      }
      return _results;
    })());
    server = new WebSocketServer({
      server: params.server,
      path: '/plugin/twadio'
    });
    return server.on('connection', function(socket) {
      var update;
      console.log('connection established, listening');
      update = function() {
        return socket.send(JSON.stringify(status, null, 2), function(err) {
          if (err) {
            return console.log('twadio send err:', err);
          }
        });
      };
      update();
      return socket.on('message', function(message) {
        var action;
        console.log('twadio message:', message);
        action = JSON.parse(message);
        switch (action.action) {
          case 'stop':
            status.mode = null;
            radio.kill('SIGTERM');
            break;
          case 'send':
            status.mode = 'send';
            startRadio("the quick brown fox jumped over the lazy dogs back");
            radio.once('update', function() {
              return update();
            });
            break;
          case 'tune':
            status.mode = 'tune';
            startRadio("30");
            radio.once('update', function() {
              return update();
            });
        }
        return update();
      });
    });
  };

  module.exports = {
    startServer: startServer
  };

}).call(this);
