// Generated by CoffeeScript 1.4.0
(function() {
  var bind, emit, parse;

  parse = function(text) {
    var defn;
    return defn = {
      freq: 14.042,
      tune: 30
    };
  };

  emit = function($item, item) {
    var defn;
    defn = parse(item.text);
    return $item.append("<div style=\"background-color:#eee; padding: 1em;\">\n	<button class=\"send\">Send</button> psk-31 on " + defn.freq + " MHz<br>\n	<button class=\"tune\">Tune</button> for " + defn.tune + " seconds<br>\n	<p class=\"caption\">status here</p>\n	<h4>Pages Ready to Send</h4>\n	<div class=\"schedule\">\n		<a href=\"#\">Jeremy McDermond NH6Z Notes</a><br>\n		<a href='#'>Ward Cunningham K9OX Notes</a>\n	</div>\n</div>");
  };

  bind = function($item, item) {
    var $page, $schedule, $send, $tune, defn, host, progress, request, socket, status;
    defn = parse(item.text);
    status = {};
    wiki.log(defn);
    $send = $item.find('button.send');
    $tune = $item.find('button.tune');
    $schedule = $item.find('div.schedule');
    $page = $item.parents('.page:first');
    host = $page.data('site') || location.host;
    if (host === 'origin' || host === 'local') {
      host = location.host;
    }
    socket = new WebSocket("ws://" + host + "/plugin/twadio");
    $item.dblclick(function() {
      return wiki.textEditor($item, item);
    });
    progress = function(m) {
      return $item.find('p.caption').html(m);
    };
    request = function(action) {
      var message;
      progress("send " + (message = JSON.stringify(action)));
      if (socket) {
        return socket.send(message);
      }
    };
    $send.on('click', function() {
      return request({
        action: status.mode === 'send' ? 'stop' : 'send'
      });
    });
    $tune.on('click', function() {
      return request({
        action: status.mode === 'tune' ? 'stop' : 'tune'
      });
    });
    socket.onopen = function() {
      return progress("opened");
    };
    socket.onmessage = function(e) {
      progress("message " + e.data);
      status = JSON.parse(e.data);
      $send.html(status.mode === 'send' ? 'Stop' : 'Send');
      return $tune.html(status.mode === 'tune' ? 'Stop' : 'Tune');
    };
    return socket.onclose = function() {
      progress("closed");
      return socket = null;
    };
  };

  if (typeof window !== "undefined" && window !== null) {
    window.plugins.twadio = {
      emit: emit,
      bind: bind
    };
  }

}).call(this);
