// Generated by CoffeeScript 1.3.3
(function() {

  window.plugins.rollup = {
    emit: function(div, item) {},
    bind: function(div, item) {
      var $row, $table, asValue, attach, col, label, reference, row, rows, slug, title, value, _i, _len, _results;
      div.dblclick(function() {
        return wiki.textEditor(div, item);
      });
      asValue = function(obj) {
        if (obj == null) {
          return NaN;
        }
        switch (obj.constructor) {
          case Number:
            return obj;
          case String:
            return +obj;
          case Array:
            return asValue(obj[0]);
          case Object:
            return asValue(obj.value);
          case Function:
            return obj();
          default:
            return NaN;
        }
      };
      attach = function(search) {
        var elem, source, _i, _len, _ref;
        _ref = wiki.getDataNodes(div);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          elem = _ref[_i];
          if ((source = $(elem).data('item')).text.indexOf(search) >= 0) {
            return source;
          }
          throw new Error("can't find dataset with caption " + search);
        }
      };
      reference = attach("Materials Summary");
      div.append("<style>\n  td.material {overflow:hidden;}\n  td.score {text-align:right; width:25px}\n</style>");
      div.append(($table = $("<table/>")));
      wiki.log('rollup', reference, reference.data, $table);
      rows = _.sortBy(reference.data, function(row) {
        return asValue(row['Total Score']);
      });
      _results = [];
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        row = rows[_i];
        label = wiki.resolveLinks("[[" + row.Material + "]]");
        slug = wiki.asSlug(row.Material);
        $table.append(($row = $("<tr class=\"" + slug + "\">\n  <td class=\"material\">" + label + "</td>")));
        _results.push((function() {
          var _j, _len1, _ref, _results1;
          _ref = reference.columns;
          _results1 = [];
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            col = _ref[_j];
            if (col === 'Material') {
              continue;
            }
            value = asValue(row[col]);
            title = "" + row.Material + "\n" + col + "\n" + (value.toFixed(2));
            _results1.push($row.append("<td class=\"score\" title=\"" + title + "\">" + (value.toFixed(0)) + "</td>"));
          }
          return _results1;
        })());
      }
      return _results;
    }
  };

}).call(this);
