// Generated by CoffeeScript 1.4.0
(function() {
  var bind, emit;

  emit = function(div, item) {
    return div.append("<div style=\"height: 10px; border-top: 2px solid lightgray; margin-top: 24px; text-align: center; position: relative; clear: both;\">\n	<span style=\"position: relative; top: -.8em; background: white; display: inline-block; color: gray; \">\n		&nbsp; " + item.text + " &nbsp;\n	</span>\n</div>");
  };

  bind = function(div, item) {
    return div.dblclick(function() {
      return wiki.textEditor(div, item);
    });
  };

  window.plugins.calendar = {
    emit: emit,
    bind: bind
  };

}).call(this);
