// Generated by CoffeeScript 1.3.3
(function() {

  window.plugins.method = {
    emit: function(div, item) {},
    bind: function(div, item) {
      var annotate, asValue, avg, calculate, candidates, elem, input, output, round, sum, _i, _len;
      input = {};
      output = {};
      asValue = function(obj) {
        if (obj == null) {
          return NaN;
        }
        switch (obj.constructor) {
          case Number:
            return obj;
          case String:
            return +obj;
          case Array:
            return asValue(obj[0]);
          case Object:
            return asValue(obj.value);
          case Function:
            return obj();
          default:
            return NaN;
        }
      };
      candidates = $(".item:lt(" + ($('.item').index(div)) + ")");
      for (_i = 0, _len = candidates.length; _i < _len; _i++) {
        elem = candidates[_i];
        elem = $(elem);
        if (elem.hasClass('radar-source')) {
          _.extend(input, elem.get(0).radarData());
        } else if (elem.hasClass('data')) {
          _.extend(input, elem.data('item').data[0]);
        }
      }
      div.addClass('radar-source');
      div.get(0).radarData = function() {
        return output;
      };
      div.mousemove(function(e) {
        return $(div).triggerHandler('thumb', $(e.target).text());
      });
      sum = function(v) {
        return _.reduce(v, function(s, n) {
          return s += n;
        });
      };
      avg = function(v) {
        return sum(v) / v.length;
      };
      round = function(n) {
        if (n == null) {
          return '?';
        }
        if (n.toString().match(/\.\d\d\d/)) {
          return n.toFixed(2);
        } else {
          return n;
        }
      };
      annotate = function(text) {
        if (text == null) {
          return '';
        }
        return " <span title=\"" + text + "\">*</span>";
      };
      calculate = function(item) {
        var allocated, dispatch, lines, list, report;
        list = [];
        allocated = 0;
        lines = item.text.split("\n");
        report = [];
        dispatch = function(list, allocated, lines, report, done) {
          var apply, args, change, color, comment, count, hours, hover, line, next_dispatch, previous, result, value, _ref, _ref1;
          color = '#eee';
          value = comment = hover = null;
          hours = '';
          line = lines.shift();
          if (line == null) {
            return done(report);
          }
          next_dispatch = function() {
            if ((value != null) && !isNaN(+value)) {
              list.push(+value);
            }
            report.push("<tr style=\"background:" + color + ";\">\n  <td style=\"width: 20%; text-align: right;\" title=\"" + (hover || '') + "\">\n    <b>" + (round(value)) + "</b>\n  <td>" + line + (annotate(comment)));
            return dispatch(list, allocated, lines, report, done);
          };
          apply = function(name, list) {
            if (name === 'SUM') {
              color = '#ddd';
              return sum(list);
            } else if (name === 'AVG') {
              color = '#ddd';
              return avg(list);
            } else if (name === 'MIN') {
              color = '#ddd';
              return _.min(list);
            } else if (name === 'MAX') {
              color = '#ddd';
              return _.max(list);
            } else {
              throw new Error("don't know how to " + name);
            }
          };
          try {
            if (args = line.match(/^([0-9.eE-]+) ([\w \/%(),-]+)$/)) {
              result = hours = +args[1];
              line = args[2];
              output[line] = value = result;
            } else if (args = line.match(/^([A-Z]+) ([\w \/%(),-]+)$/)) {
              _ref = [apply(args[1], list), [], list.length], value = _ref[0], list = _ref[1], count = _ref[2];
              hover = "" + args[1] + " of " + count + " numbers\n= " + value;
              line = args[2];
              if ((output[line] != null) || (input[line] != null)) {
                previous = asValue(output[line] || input[line]);
                if (Math.abs(change = value / previous - 1) > 0.0001) {
                  comment = "previously " + previous + "\nΔ " + (round(change * 100)) + "%";
                }
              }
              output[line] = value;
            } else if (args = line.match(/^([A-Z]+)$/)) {
              _ref1 = [apply(args[1], list), [], list.length], value = _ref1[0], list = _ref1[1], count = _ref1[2];
              hover = "" + args[1] + " of " + count + " numbers\n= " + value;
            } else if (line.match(/^[0-9\.eE-]+$/)) {
              value = +line;
              line = '';
            } else if (line.match(/^([\w \/%(),-]+)$/)) {
              if (output[line] != null) {
                value = output[line];
              } else if (input[line] != null) {
                value = asValue(input[line]);
              } else {
                color = '#edd';
                comment = "can't find value of '" + line + "'";
              }
            } else {
              color = '#edd';
              comment = "can't parse '" + line + "'";
            }
          } catch (err) {
            color = '#edd';
            value = null;
            comment = err.message;
          }
          return next_dispatch();
        };
        return dispatch(list, allocated, lines, report, function(report) {
          var table, text;
          text = report.join("\n");
          table = $('<table style="width:100%; background:#eee; padding:.8em;"/>').html(text);
          div.append(table);
          return div.dblclick(function() {
            return wiki.textEditor(div, item);
          });
        });
      };
      return calculate(item);
    }
  };

}).call(this);
